version: '3'

services:
  nextjs:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000" # Map the container's port 3000 to the host machine's port 80
    volumes:
      - .:/app # Bind the current directory to the /app directory inside the container
      - /app/node_modules # Prevent overwriting node_modules with the host's copy
      - /app/.next # Prevent overwriting .next directory
    environment:
      - NODE_ENV=production
    command: npm run start # Run the application
